-- MySQL Script generated by MySQL Workbench
-- Thu Jul  7 22:54:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estado` (
  `cod_estado` INT NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `sigla_estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`cod_estado`),
  UNIQUE INDEX `cod_estado_UNIQUE` (`cod_estado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cod_cliente` INT NOT NULL,
  `sexo` INT NOT NULL,
  `idade` INT NOT NULL,
  `qtd_filhos` INT NOT NULL,
  `estado_civil` INT NOT NULL,
  `hipertensao` INT NOT NULL,
  `diabetes` INT NOT NULL,
  `cod_estado` INT NOT NULL,
  PRIMARY KEY (`cod_cliente`),
  UNIQUE INDEX `cod_cliente_UNIQUE` (`cod_cliente` ASC) VISIBLE,
  INDEX `fk_cliente_estado1_idx` (`cod_estado` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_estado1`
    FOREIGN KEY (`cod_estado`)
    REFERENCES `mydb`.`estado` (`cod_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`produto` (
  `produto` VARCHAR(45) NOT NULL,
  `cod_classe_produto` INT NOT NULL,
  `classe_produto` VARCHAR(100) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `cod_produto` INT NOT NULL,
  PRIMARY KEY (`cod_produto`),
  UNIQUE INDEX `cod_produto_UNIQUE` (`cod_produto` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`compra` (
  `qtd_produto` INT NOT NULL,
  `valor_unitario` DECIMAL(10,2) NOT NULL,
  `valor_total_compra` DECIMAL(10,2) NOT NULL,
  `cod_cliente` INT NOT NULL,
  `cod_produto` INT NOT NULL,
  INDEX `fk_compra_cliente_idx` (`cod_cliente` ASC) VISIBLE,
  INDEX `fk_compra_produto1_idx` (`cod_produto` ASC) VISIBLE,
  CONSTRAINT `fk_compra_cliente`
    FOREIGN KEY (`cod_cliente`)
    REFERENCES `mydb`.`cliente` (`cod_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compra_produto1`
    FOREIGN KEY (`cod_produto`)
    REFERENCES `mydb`.`produto` (`cod_produto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
